declare namespace SymbiosisUI {
  type IconName =
    | "symbiosis-chevron-down"
    | "symbiosis-minus"
    | "symbiosis-check"
    | "symbiosis-kebab"
    | "symbiosis-sort-rows-asc"
    | "symbiosis-sort-rows-desc"
    | "symbiosis-select"
    | "symbiosis-dots"
    | "symbiosis-chevron-left"
    | "symbiosis-chevron-right"
    | "symbiosis-chevron-down"
    | "symbiosis-minus"
    | "symbiosis-check"
    | "symbiosis-exclamation-circle"
    | "symbiosis-help-circle"
    | "symbiosis-plus"
    | "symbiosis-loader"
    | "symbiosis-toast-success"
    | "symbiosis-toast-info"
    | "symbiosis-toast-warning"
    | "symbiosis-toast-destructive"
    | "symbiosis-search"
    | "symbiosis-x";
}
