// src/components/Icon/IconContext.tsx
import React from "react";

type IconContextType = {
  publicDir?: string;
};

export const IconContext = React.createContext<IconContextType>({
  publicDir: "",
});

// Generated by symbiosis ui plugin
const DEFAULT_PATH_PREFIX = "symbiosis-assets";

export const IconProvider: React.FC<IconContextType & { children: React.ReactNode }> = ({ publicDir, children }) => (
  <IconContext.Provider
    value={{
      publicDir: `${publicDir ?? ""}/${DEFAULT_PATH_PREFIX}/sprite.svg`,
    }}
  >
    {children}
  </IconContext.Provider>
);
