import React from "react";

type SymbiosisContextType = {
  publicDir?: string;
  scheme?: "dark" | "light";
};

export const SymbiosisContext = React.createContext<SymbiosisContextType>({
  publicDir: "",
});

// Generated by symbiosis ui plugin
const DEFAULT_PATH_PREFIX = "symbiosis-assets";

export const SymbiosisProvider: React.FC<
  SymbiosisContextType & { children: React.ReactNode }
> = ({ publicDir, scheme = "dark", children }) => {
  React.useEffect(() => {
    if (!scheme) return;
    document.body.classList.remove("dark-scheme", "light-scheme");
    document.body.classList.add(`${scheme}-scheme`);
  }, [scheme]);

  return (
    <SymbiosisContext.Provider
      value={{
        publicDir: `${publicDir ?? ""}/${DEFAULT_PATH_PREFIX}/sprite.svg`,
        scheme,
      }}
    >
      {children}
    </SymbiosisContext.Provider>
  );
};
